SAMPLES: "WT_gDNA_Rep1"
THREADS: 7
MEMORY: "70g"
FILTER:
  cutadapt:
      R1_5prime_cut: 21 # -u
      R1_3prime_cut: -0 # -u
      R2_5prime_cut: 30 # -U
      R2_3prime_cut: -0 # -U
      adapter_R1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC # -a
      adapter_R2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT # -A
      quality-filter: 20 # -q
      minimum-overlap: 3 # -O (default: 3)
      minimum-length: 30 # -m
      maximum-length: 100 # -M
      extra-params:
# NOTE: reference genome-specific mapping parameters
MAPPING:
      alignments: 10 # "In -k <N> mode, Bowtie 2 searches for up to N distinct, valid alignments for each read"
      reference: "data/index/TAIR10_chr_all"
      MAPQunique: 23 # -q
      MAPQmaxi: 2 # -q
      sortMemory: "10G"
COVERAGE:
      normalizeUsing: "CPM"
      ignoreForNormalization: "mitochondria chloroplast" # Reference genome-specific parameter
      binSize: 1
      genomeBinSize: 10000
      genomeBinName: "10kb"

# NEBNext adapter and universal primer for Illumina:
# https://international.neb.com/-/media/catalog/datacards-or-manuals/manuale7335.pdf
# https://www.biostars.org/p/149301/
# https://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq
# http://bioinformatics.cvr.ac.uk/blog/illumina-adapter-and-primer-sequences/
# TruSeq adapters:
# http://emea.support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html
